// CSS @keyframes animation polyfill for KHtmlLite.
// Injected after the base ES3 polyfill. Reads keyframes extracted by
// PageLoader (window.__cssKeyframes) and drives them with requestAnimationFrame.
// Supports opacity, transform (translate/rotate/scale), pixel lengths, and
// colors. Deliberately small and ES3-only so it runs on KJS without transpilation.
static const char *kCssAnimPolyfill =
"(function(){\n"
"  var kf = window.__cssKeyframes || {};\n"
"  if (!window.requestAnimationFrame) return;\n"
"  var runners = [];\n"
"  var scanTimer = null;\n"
"\n"
"  function parsePx(v) {\n"
"    if (!v) return 0;\n"
"    var n = parseFloat(v);\n"
"    return isNaN(n) ? 0 : n;\n"
"  }\n"
"\n"
"  function parseColor(v) {\n"
"    if (!v) return null;\n"
"    v = v.replace(/\\s+/g, '');\n"
"    if (v.charAt(0) === '#') {\n"
"      var h = v.substring(1);\n"
"      if (h.length === 3) h = h.charAt(0)+h.charAt(0)+h.charAt(1)+h.charAt(1)+h.charAt(2)+h.charAt(2);\n"
"      if (h.length === 6) return [parseInt(h.substring(0,2),16), parseInt(h.substring(2,4),16), parseInt(h.substring(4,6),16)];\n"
"    }\n"
"    var m = v.match(/rgb\\((\\d+),(\\d+),(\\d+)\\)/);\n"
"    if (m) return [parseInt(m[1]), parseInt(m[2]), parseInt(m[3])];\n"
"    return null;\n"
"  }\n"
"\n"
"  function lerp(a, b, t) { return a + (b - a) * t; }\n"
"\n"
"  function lerpColor(c1, c2, t) {\n"
"    if (!c1 || !c2) return null;\n"
"    return 'rgb(' + Math.round(lerp(c1[0],c2[0],t)) + ',' + Math.round(lerp(c1[1],c2[1],t)) + ',' + Math.round(lerp(c1[2],c2[2],t)) + ')';\n"
"  }\n"
"\n"
"  function parseTransform(v) {\n"
"    var r = {tx:0, ty:0, rot:0, scale:1};\n"
"    if (!v) return r;\n"
"    var m;\n"
"    m = v.match(/translate\\(([^,)]+)(?:,([^)]+))?\\)/);\n"
"    if (m) { r.tx = parsePx(m[1]); r.ty = m[2] ? parsePx(m[2]) : 0; }\n"
"    m = v.match(/translateX\\(([^)]+)\\)/);\n"
"    if (m) r.tx = parsePx(m[1]);\n"
"    m = v.match(/translateY\\(([^)]+)\\)/);\n"
"    if (m) r.ty = parsePx(m[1]);\n"
"    m = v.match(/rotate\\(([^)]+)deg\\)/);\n"
"    if (m) r.rot = parseFloat(m[1]);\n"
"    m = v.match(/scale\\(([^)]+)\\)/);\n"
"    if (m) r.scale = parseFloat(m[1]);\n"
"    return r;\n"
"  }\n"
"\n"
"  function fmtTransform(t) {\n"
"    return 'translate(' + t.tx + 'px,' + t.ty + 'px) rotate(' + t.rot + 'deg) scale(' + t.scale + ')';\n"
"  }\n"
"\n"
"  function lerpTransform(a, b, t) {\n"
"    return {tx:lerp(a.tx,b.tx,t), ty:lerp(a.ty,b.ty,t), rot:lerp(a.rot,b.rot,t), scale:lerp(a.scale,b.scale,t)};\n"
"  }\n"
"\n"
"  // Parse a keyframe's cssText into {opacity, transform, width, height, left, top, color, backgroundColor, fontSize}\n"
"  function parseFrameProps(cssText) {\n"
"    var p = {};\n"
"    if (!cssText) return p;\n"
"    var decls = cssText.split(';');\n"
"    for (var i = 0; i < decls.length; i++) {\n"
"      var kv = decls[i].split(':');\n"
"      if (kv.length < 2) continue;\n"
"      var prop = kv[0].replace(/^\\s+|\\s+$/g, '').toLowerCase();\n"
"      var val = kv.slice(1).join(':').replace(/^\\s+|\\s+$/g, '');\n"
"      if (prop === 'opacity') p.opacity = parseFloat(val);\n"
"      else if (prop === 'transform' || prop === '-webkit-transform') p.transform = val;\n"
"      else if (prop === 'width') p.width = val;\n"
"      else if (prop === 'height') p.height = val;\n"
"      else if (prop === 'left') p.left = val;\n"
"      else if (prop === 'top') p.top = val;\n"
"      else if (prop === 'color') p.color = val;\n"
"      else if (prop === 'background-color' || prop === 'background') p.backgroundColor = val;\n"
"      else if (prop === 'font-size') p.fontSize = val;\n"
"    }\n"
"    return p;\n"
"  }\n"
"\n"
"  function applyProps(el, props) {\n"
"    try {\n"
"      if (props.opacity !== undefined) el.style.opacity = props.opacity;\n"
"      if (props.transform !== undefined) el.style.transform = props.transform;\n"
"      if (props.width !== undefined) el.style.width = props.width;\n"
"      if (props.height !== undefined) el.style.height = props.height;\n"
"      if (props.left !== undefined) el.style.left = props.left;\n"
"      if (props.top !== undefined) el.style.top = props.top;\n"
"      if (props.color !== undefined) el.style.color = props.color;\n"
"      if (props.backgroundColor !== undefined) el.style.backgroundColor = props.backgroundColor;\n"
"      if (props.fontSize !== undefined) el.style.fontSize = props.fontSize;\n"
"    } catch(e) {}\n"
"  }\n"
"\n"
"  function blendProps(a, b, t) {\n"
"    var r = {};\n"
"    if (a.opacity !== undefined && b.opacity !== undefined) r.opacity = lerp(a.opacity, b.opacity, t);\n"
"    if (a.transform !== undefined && b.transform !== undefined) r.transform = fmtTransform(lerpTransform(parseTransform(a.transform), parseTransform(b.transform), t));\n"
"    if (a.width !== undefined && b.width !== undefined) r.width = lerp(parsePx(a.width), parsePx(b.width), t) + 'px';\n"
"    if (a.height !== undefined && b.height !== undefined) r.height = lerp(parsePx(a.height), parsePx(b.height), t) + 'px';\n"
"    if (a.left !== undefined && b.left !== undefined) r.left = lerp(parsePx(a.left), parsePx(b.left), t) + 'px';\n"
"    if (a.top !== undefined && b.top !== undefined) r.top = lerp(parsePx(a.top), parsePx(b.top), t) + 'px';\n"
"    var c1 = parseColor(a.color), c2 = parseColor(b.color);\n"
"    if (c1 && c2) r.color = lerpColor(c1, c2, t);\n"
"    var bc1 = parseColor(a.backgroundColor), bc2 = parseColor(b.backgroundColor);\n"
"    if (bc1 && bc2) r.backgroundColor = lerpColor(bc1, bc2, t);\n"
"    if (a.fontSize !== undefined && b.fontSize !== undefined) r.fontSize = lerp(parsePx(a.fontSize), parsePx(b.fontSize), t) + 'px';\n"
"    return r;\n"
"  }\n"
"\n"
"  function findFrames(name) {\n"
"    return kf[name] || null;\n"
"  }\n"
"\n"
"  function getAnimConfig(el) {\n"
"    var name = '', dur = 1000, delay = 0, iter = 1, dir = 'normal', fill = 'none', tf = 'ease';\n"
"    try {\n"
"      var cs = window.getComputedStyle ? window.getComputedStyle(el) : null;\n"
"      if (cs) {\n"
"        name = cs.animationName || cs.getPropertyValue('animation-name') || '';\n"
"        dur = parseFloat(cs.animationDuration || cs.getPropertyValue('animation-duration') || '1s') * 1000;\n"
"        delay = parseFloat(cs.animationDelay || cs.getPropertyValue('animation-delay') || '0s') * 1000;\n"
"        var ic = cs.animationIterationCount || cs.getPropertyValue('animation-iteration-count') || '1';\n"
"        iter = (ic === 'infinite') ? -1 : parseInt(ic);\n"
"        dir = cs.animationDirection || cs.getPropertyValue('animation-direction') || 'normal';\n"
"        fill = cs.animationFillMode || cs.getPropertyValue('animation-fill-mode') || 'none';\n"
"        tf = cs.animationTimingFunction || cs.getPropertyValue('animation-timing-function') || 'ease';\n"
"      }\n"
"    } catch(e) {}\n"
"    if (!name && el.style && el.style.animationName) name = el.style.animationName;\n"
"    if (!name || name === 'none') return null;\n"
"    return {name:name, dur:dur, delay:delay, iter:iter, dir:dir, fill:fill, tf:tf};\n"
"  }\n"
"\n"
"  function ease(t, func) {\n"
"    if (func === 'linear') return t;\n"
"    if (func === 'ease-in') return t * t;\n"
"    if (func === 'ease-out') return t * (2 - t);\n"
"    // ease-in-out and default ease\n"
"    return t < 0.5 ? 2 * t * t : -1 + (4 - 2 * t) * t;\n"
"  }\n"
"\n"
"  function scanElements() {\n"
"    var all = document.getElementsByTagName('*');\n"
"    var now = Date.now();\n"
"    for (var i = 0; i < all.length; i++) {\n"
"      var el = all[i];\n"
"      if (el.__animHandled) continue;\n"
"      var cfg = getAnimConfig(el);\n"
"      if (!cfg) continue;\n"
"      var frames = findFrames(cfg.name);\n"
"      if (!frames || frames.length < 2) continue;\n"
"      el.__animHandled = true;\n"
"      runners.push({el:el, cfg:cfg, frames:frames, start:now + cfg.delay, elapsed:0, done:false});\n"
"    }\n"
"  }\n"
"\n"
"  function tick(ts) {\n"
"    var now = Date.now();\n"
"    for (var i = runners.length - 1; i >= 0; i--) {\n"
"      var r = runners[i];\n"
"      if (now < r.start) continue;\n"
"      var elapsed = now - r.start;\n"
"      var dur = r.cfg.dur > 0 ? r.cfg.dur : 1;\n"
"      var progress;\n"
"      if (r.cfg.iter === -1) {\n"
"        progress = (elapsed % dur) / dur;\n"
"      } else {\n"
"        var total = dur * r.cfg.iter;\n"
"        if (elapsed >= total) {\n"
"          progress = 1;\n"
"          if (r.cfg.fill === 'forwards' || r.cfg.fill === 'both') {\n"
"            applyFrame(r, 1);\n"
"          }\n"
"          r.done = true;\n"
"          runners.splice(i, 1);\n"
"          continue;\n"
"        }\n"
"        progress = (elapsed % dur) / dur;\n"
"      }\n"
"      if (r.cfg.dir === 'reverse' || (r.cfg.dir === 'alternate' && Math.floor(elapsed / dur) % 2 === 1)) progress = 1 - progress;\n"
"      progress = ease(progress, r.cfg.tf);\n"
"      applyFrame(r, progress);\n"
"    }\n"
"    if (runners.length > 0 || !scanDone) {\n"
"      window.requestAnimationFrame(tick);\n"
"    }\n"
"  }\n"
"\n"
"  function applyFrame(r, progress) {\n"
"    var frames = r.frames;\n"
"    var fi = 0;\n"
"    for (var j = 0; j < frames.length - 1; j++) {\n"
"      if (progress >= frames[j].offset && progress <= frames[j+1].offset) { fi = j; break; }\n"
"    }\n"
"    var f1 = frames[fi], f2 = frames[Math.min(fi+1, frames.length-1)];\n"
"    var localT = (f2.offset > f1.offset) ? (progress - f1.offset) / (f2.offset - f1.offset) : 0;\n"
"    var p1 = parseFrameProps(f1.cssText), p2 = parseFrameProps(f2.cssText);\n"
"    var blended = blendProps(p1, p2, localT);\n"
"    applyProps(r.el, blended);\n"
"  }\n"
"\n"
"  var scanDone = false;\n"
"  function start() {\n"
"    scanElements();\n"
"    scanDone = true;\n"
"    if (runners.length > 0) window.requestAnimationFrame(tick);\n"
"    // Rescan once more after 1s for late-added elements\n"
"    setTimeout(function() { scanElements(); if (runners.length > 0) window.requestAnimationFrame(tick); }, 1000);\n"
"  }\n"
"\n"
"  if (document.readyState === 'complete' || document.readyState === 'interactive') {\n"
"    setTimeout(start, 50);\n"
"  } else {\n"
"    window.addEventListener('load', function() { setTimeout(start, 50); });\n"
"  }\n"
"})();\n";
